// Mocks generated by Mockito 5.3.0 from annotations
// in oic_next_to_you/test/features/auth/data/repositories/otp_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:firebase_auth/firebase_auth.dart' as _i4;
import 'package:firebase_auth_platform_interface/firebase_auth_platform_interface.dart'
    as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:oic_next_to_you/common/data/datasources/internet_connection_datasource.dart'
    as _i5;
import 'package:oic_next_to_you/common/domain/entities/user/user.dart' as _i12;
import 'package:oic_next_to_you/features/auth/data/datasources/local_credential_datasource.dart'
    as _i7;
import 'package:oic_next_to_you/features/auth/data/datasources/network_otp_datasource.dart'
    as _i8;
import 'package:oic_next_to_you/features/auth/data/models/request_otp/request_otp_request.dart'
    as _i9;
import 'package:oic_next_to_you/features/auth/data/models/request_otp/request_otp_response.dart'
    as _i2;
import 'package:oic_next_to_you/features/auth/data/models/verify_otp/verify_otp_request.dart'
    as _i10;
import 'package:oic_next_to_you/features/auth/data/models/verify_otp/verify_otp_response.dart'
    as _i3;
import 'package:oic_next_to_you/features/auth/domain/repositories/user_repository.dart'
    as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRequestOtpResponse_0 extends _i1.SmartFake
    implements _i2.RequestOtpResponse {
  _FakeRequestOtpResponse_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeVerifyOtpResponse_1 extends _i1.SmartFake
    implements _i3.VerifyOtpResponse {
  _FakeVerifyOtpResponse_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeUserMetadata_2 extends _i1.SmartFake implements _i4.UserMetadata {
  _FakeUserMetadata_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeMultiFactor_3 extends _i1.SmartFake implements _i4.MultiFactor {
  _FakeMultiFactor_3(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeIdTokenResult_4 extends _i1.SmartFake implements _i4.IdTokenResult {
  _FakeIdTokenResult_4(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeUserCredential_5 extends _i1.SmartFake
    implements _i4.UserCredential {
  _FakeUserCredential_5(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeConfirmationResult_6 extends _i1.SmartFake
    implements _i4.ConfirmationResult {
  _FakeConfirmationResult_6(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeUser_7 extends _i1.SmartFake implements _i4.User {
  _FakeUser_7(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [InternetConnectionDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockInternetConnectionDatasource extends _i1.Mock
    implements _i5.InternetConnectionDatasource {
  MockInternetConnectionDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> isConnected() =>
      (super.noSuchMethod(Invocation.method(#isConnected, []),
          returnValue: _i6.Future<bool>.value(false)) as _i6.Future<bool>);
}

/// A class which mocks [LocalCredentialDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalCredentialDatasource extends _i1.Mock
    implements _i7.LocalCredentialDatasource {
  MockLocalCredentialDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.PhoneAuthCredential? getCredentialFromPhoneNumber(String? phoneNumber) =>
      (super.noSuchMethod(
              Invocation.method(#getCredentialFromPhoneNumber, [phoneNumber]))
          as _i4.PhoneAuthCredential?);
  @override
  dynamic setCredentialOfPhoneNumber(
          {String? phoneNumber, _i4.PhoneAuthCredential? credential}) =>
      super.noSuchMethod(Invocation.method(#setCredentialOfPhoneNumber, [],
          {#phoneNumber: phoneNumber, #credential: credential}));
}

/// A class which mocks [NetworkOtpDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkOtpDatasource extends _i1.Mock
    implements _i8.NetworkOtpDatasource {
  MockNetworkOtpDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.RequestOtpResponse> requestOtp(
          _i9.RequestOtpRequest? request) =>
      (super.noSuchMethod(Invocation.method(#requestOtp, [request]),
              returnValue: _i6.Future<_i2.RequestOtpResponse>.value(
                  _FakeRequestOtpResponse_0(
                      this, Invocation.method(#requestOtp, [request]))))
          as _i6.Future<_i2.RequestOtpResponse>);
  @override
  _i6.Future<_i3.VerifyOtpResponse> verifyOtp(_i10.VerifyOtpRequest? request) =>
      (super.noSuchMethod(Invocation.method(#verifyOtp, [request]),
              returnValue: _i6.Future<_i3.VerifyOtpResponse>.value(
                  _FakeVerifyOtpResponse_1(
                      this, Invocation.method(#verifyOtp, [request]))))
          as _i6.Future<_i3.VerifyOtpResponse>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i11.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i12.User?> getLoggedInUser() => (super.noSuchMethod(
      Invocation.method(#getLoggedInUser, []),
      returnValue: _i6.Future<_i12.User?>.value()) as _i6.Future<_i12.User?>);
  @override
  _i6.Future<bool> setLoggedInUser(_i12.User? user) =>
      (super.noSuchMethod(Invocation.method(#setLoggedInUser, [user]),
          returnValue: _i6.Future<bool>.value(false)) as _i6.Future<bool>);
}

/// A class which mocks [PhoneAuthCredential].
///
/// See the documentation for Mockito's code generation for more information.
class MockPhoneAuthCredential extends _i1.Mock
    implements _i4.PhoneAuthCredential {
  MockPhoneAuthCredential() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get providerId =>
      (super.noSuchMethod(Invocation.getter(#providerId), returnValue: '')
          as String);
  @override
  String get signInMethod =>
      (super.noSuchMethod(Invocation.getter(#signInMethod), returnValue: '')
          as String);
  @override
  Map<String, dynamic> asMap() =>
      (super.noSuchMethod(Invocation.method(#asMap, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
}

/// A class which mocks [FirebaseAuthException].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAuthException extends _i1.Mock
    implements _i4.FirebaseAuthException {
  MockFirebaseAuthException() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get plugin =>
      (super.noSuchMethod(Invocation.getter(#plugin), returnValue: '')
          as String);
  @override
  String get code =>
      (super.noSuchMethod(Invocation.getter(#code), returnValue: '') as String);
}

/// A class which mocks [UserCredential].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserCredential extends _i1.Mock implements _i4.UserCredential {
  MockUserCredential() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i4.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get emailVerified =>
      (super.noSuchMethod(Invocation.getter(#emailVerified), returnValue: false)
          as bool);
  @override
  bool get isAnonymous =>
      (super.noSuchMethod(Invocation.getter(#isAnonymous), returnValue: false)
          as bool);
  @override
  _i4.UserMetadata get metadata => (super.noSuchMethod(
          Invocation.getter(#metadata),
          returnValue: _FakeUserMetadata_2(this, Invocation.getter(#metadata)))
      as _i4.UserMetadata);
  @override
  List<_i4.UserInfo> get providerData =>
      (super.noSuchMethod(Invocation.getter(#providerData),
          returnValue: <_i4.UserInfo>[]) as List<_i4.UserInfo>);
  @override
  String get uid =>
      (super.noSuchMethod(Invocation.getter(#uid), returnValue: '') as String);
  @override
  _i4.MultiFactor get multiFactor =>
      (super.noSuchMethod(Invocation.getter(#multiFactor),
              returnValue:
                  _FakeMultiFactor_3(this, Invocation.getter(#multiFactor)))
          as _i4.MultiFactor);
  @override
  _i6.Future<void> delete() => (super.noSuchMethod(
      Invocation.method(#delete, []),
      returnValue: _i6.Future<void>.value(),
      returnValueForMissingStub: _i6.Future<void>.value()) as _i6.Future<void>);
  @override
  _i6.Future<String> getIdToken([bool? forceRefresh = false]) =>
      (super.noSuchMethod(Invocation.method(#getIdToken, [forceRefresh]),
          returnValue: _i6.Future<String>.value('')) as _i6.Future<String>);
  @override
  _i6.Future<_i4.IdTokenResult> getIdTokenResult(
          [bool? forceRefresh = false]) =>
      (super.noSuchMethod(Invocation.method(#getIdTokenResult, [forceRefresh]),
          returnValue: _i6.Future<_i4.IdTokenResult>.value(_FakeIdTokenResult_4(
              this,
              Invocation.method(#getIdTokenResult, [forceRefresh])))) as _i6
          .Future<_i4.IdTokenResult>);
  @override
  _i6.Future<_i4.UserCredential> linkWithCredential(
          _i4.AuthCredential? credential) =>
      (super.noSuchMethod(Invocation.method(#linkWithCredential, [credential]),
              returnValue: _i6.Future<_i4.UserCredential>.value(
                  _FakeUserCredential_5(this,
                      Invocation.method(#linkWithCredential, [credential]))))
          as _i6.Future<_i4.UserCredential>);
  @override
  _i6.Future<_i4.UserCredential> linkWithPopup(_i13.AuthProvider? provider) =>
      (super.noSuchMethod(Invocation.method(#linkWithPopup, [provider]),
              returnValue: _i6.Future<_i4.UserCredential>.value(
                  _FakeUserCredential_5(
                      this, Invocation.method(#linkWithPopup, [provider]))))
          as _i6.Future<_i4.UserCredential>);
  @override
  _i6.Future<_i4.ConfirmationResult> linkWithPhoneNumber(String? phoneNumber,
          [_i4.RecaptchaVerifier? verifier]) =>
      (super.noSuchMethod(
              Invocation.method(#linkWithPhoneNumber, [phoneNumber, verifier]),
              returnValue: _i6.Future<_i4.ConfirmationResult>.value(
                  _FakeConfirmationResult_6(
                      this,
                      Invocation.method(
                          #linkWithPhoneNumber, [phoneNumber, verifier]))))
          as _i6.Future<_i4.ConfirmationResult>);
  @override
  _i6.Future<_i4.UserCredential> reauthenticateWithCredential(
          _i4.AuthCredential? credential) =>
      (super.noSuchMethod(
              Invocation.method(#reauthenticateWithCredential, [credential]),
              returnValue: _i6.Future<_i4.UserCredential>.value(
                  _FakeUserCredential_5(
                      this,
                      Invocation.method(
                          #reauthenticateWithCredential, [credential]))))
          as _i6.Future<_i4.UserCredential>);
  @override
  _i6.Future<void> reload() => (super.noSuchMethod(
      Invocation.method(#reload, []),
      returnValue: _i6.Future<void>.value(),
      returnValueForMissingStub: _i6.Future<void>.value()) as _i6.Future<void>);
  @override
  _i6.Future<void> sendEmailVerification(
          [_i4.ActionCodeSettings? actionCodeSettings]) =>
      (super.noSuchMethod(
              Invocation.method(#sendEmailVerification, [actionCodeSettings]),
              returnValue: _i6.Future<void>.value(),
              returnValueForMissingStub: _i6.Future<void>.value())
          as _i6.Future<void>);
  @override
  _i6.Future<_i4.User> unlink(String? providerId) =>
      (super.noSuchMethod(Invocation.method(#unlink, [providerId]),
              returnValue: _i6.Future<_i4.User>.value(
                  _FakeUser_7(this, Invocation.method(#unlink, [providerId]))))
          as _i6.Future<_i4.User>);
  @override
  _i6.Future<void> updateEmail(String? newEmail) => (super.noSuchMethod(
      Invocation.method(#updateEmail, [newEmail]),
      returnValue: _i6.Future<void>.value(),
      returnValueForMissingStub: _i6.Future<void>.value()) as _i6.Future<void>);
  @override
  _i6.Future<void> updatePassword(String? newPassword) => (super.noSuchMethod(
      Invocation.method(#updatePassword, [newPassword]),
      returnValue: _i6.Future<void>.value(),
      returnValueForMissingStub: _i6.Future<void>.value()) as _i6.Future<void>);
  @override
  _i6.Future<void> updatePhoneNumber(
          _i4.PhoneAuthCredential? phoneCredential) =>
      (super.noSuchMethod(
              Invocation.method(#updatePhoneNumber, [phoneCredential]),
              returnValue: _i6.Future<void>.value(),
              returnValueForMissingStub: _i6.Future<void>.value())
          as _i6.Future<void>);
  @override
  _i6.Future<void> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(Invocation.method(#updateDisplayName, [displayName]),
              returnValue: _i6.Future<void>.value(),
              returnValueForMissingStub: _i6.Future<void>.value())
          as _i6.Future<void>);
  @override
  _i6.Future<void> updatePhotoURL(String? photoURL) => (super.noSuchMethod(
      Invocation.method(#updatePhotoURL, [photoURL]),
      returnValue: _i6.Future<void>.value(),
      returnValueForMissingStub: _i6.Future<void>.value()) as _i6.Future<void>);
  @override
  _i6.Future<void> updateProfile({String? displayName, String? photoURL}) =>
      (super.noSuchMethod(
              Invocation.method(#updateProfile, [],
                  {#displayName: displayName, #photoURL: photoURL}),
              returnValue: _i6.Future<void>.value(),
              returnValueForMissingStub: _i6.Future<void>.value())
          as _i6.Future<void>);
  @override
  _i6.Future<void> verifyBeforeUpdateEmail(String? newEmail,
          [_i4.ActionCodeSettings? actionCodeSettings]) =>
      (super.noSuchMethod(
              Invocation.method(
                  #verifyBeforeUpdateEmail, [newEmail, actionCodeSettings]),
              returnValue: _i6.Future<void>.value(),
              returnValueForMissingStub: _i6.Future<void>.value())
          as _i6.Future<void>);
}
