// Mocks generated by Mockito 5.3.0 from annotations
// in oic_next_to_you/test/features/auth/data/repositories/user_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:oic_next_to_you/features/auth/data/datasources/local_logged_in_user_datasource.dart'
    as _i2;
import 'package:oic_next_to_you/features/auth/data/models/logged_in_user/logged_in_user.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LocalLoggedInUserDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalLoggedInUserDatasource extends _i1.Mock
    implements _i2.LocalLoggedInUserDatasource {
  MockLocalLoggedInUserDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.LoggedInUser?> getLoggedInUser() =>
      (super.noSuchMethod(Invocation.method(#getLoggedInUser, []),
              returnValue: _i3.Future<_i4.LoggedInUser?>.value())
          as _i3.Future<_i4.LoggedInUser?>);
  @override
  _i3.Future<bool> setLoggedInUser(_i4.LoggedInUser? user) =>
      (super.noSuchMethod(Invocation.method(#setLoggedInUser, [user]),
          returnValue: _i3.Future<bool>.value(false)) as _i3.Future<bool>);
}
