// Mocks generated by Mockito 5.3.0 from annotations
// in oic_next_to_you/test/features/auth/presentation/providers/splash_screen_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:oic_next_to_you/common/domain/entities/user/user.dart' as _i5;
import 'package:oic_next_to_you/features/auth/domain/repositories/user_repository.dart'
    as _i2;
import 'package:oic_next_to_you/features/auth/domain/usecases/get_logged_in_user.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserRepository_0 extends _i1.SmartFake
    implements _i2.UserRepository {
  _FakeUserRepository_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [GetLoggedInUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLoggedInUser extends _i1.Mock implements _i3.GetLoggedInUser {
  MockGetLoggedInUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserRepository get userRepository => (super.noSuchMethod(
          Invocation.getter(#userRepository),
          returnValue:
              _FakeUserRepository_0(this, Invocation.getter(#userRepository)))
      as _i2.UserRepository);
  @override
  _i4.Future<_i5.User?> call() =>
      (super.noSuchMethod(Invocation.method(#call, []),
          returnValue: _i4.Future<_i5.User?>.value()) as _i4.Future<_i5.User?>);
}
