// Mocks generated by Mockito 5.3.0 from annotations
// in oic_next_to_you/test/features/auth/domain/usecases/get_logged_in_user_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:oic_next_to_you/common/domain/entities/user/user.dart' as _i4;
import 'package:oic_next_to_you/features/auth/domain/repositories/user_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i2.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.User?> getLoggedInUser() =>
      (super.noSuchMethod(Invocation.method(#getLoggedInUser, []),
          returnValue: _i3.Future<_i4.User?>.value()) as _i3.Future<_i4.User?>);
  @override
  _i3.Future<bool> setLoggedInUser(_i4.User? user) =>
      (super.noSuchMethod(Invocation.method(#setLoggedInUser, [user]),
          returnValue: _i3.Future<bool>.value(false)) as _i3.Future<bool>);
}
